"""Fastlane Delivery contracts for tasks, evidence, repository, and release.

The package consumes already-observed canonical records and explicit Define or
Design projections. It performs no I/O, mutation, routing, approval,
authorization, publication, or AWS operation.
"""

from .evidence import (
    EVIDENCE_PATTERN,
    PROPERTY_EXECUTION_HEADERS,
    PROPERTY_TEST_EVIDENCE_DESTINATION,
    PROPERTY_TEST_EVIDENCE_HEADING,
    TASK_COMPLETION_EVIDENCE_STATUSES,
    evidence_timestamp,
    parse_observed_property_run,
    parse_property_test_evidence,
    parse_task_completion_evidence,
    parse_verification_matrix,
    replay_evidence_matches_contract,
    require_durable_evidence_source,
    require_explicit_evidence_value,
    task_property_execution_table,
    technology_version_policy_allows,
    validate_done_evidence,
    validate_done_property_evidence,
    validate_task_property_execution_projection,
)
from .models import (
    ApprovedDeliveryContract,
    ApprovedSpikeContract,
    ApprovedTaskContract,
    CheckpointReceiptRow,
    DeliveryValidationPolicy,
    HarnessExecutionRow,
    InspectedTask,
    PropertyExecutionRow,
    PropertyTestEvidenceRow,
    TaskCompletionEvidenceRow,
    TaskRequirementCoverage,
    TaskRequirementCoverageResult,
    TaskSummary,
)
from .release import parse_release_decision_record
from .repository import (
    explicit_human_approver,
    external_target_contains,
    marked_receipt,
    parse_checkpoint_git_receipt,
    parse_checkpoint_rows,
    validate_gate_b_execution_binding,
)
from .tasks import (
    declared_task_waivers,
    derive_task_requirement_coverage,
    inspect_task_blocks,
    inspect_task_sections,
    missing_current_property_task_coverage,
    task_requirement_evidence_dispositions,
    task_requirement_rules,
    task_waiver_rows,
    validate_task_records,
)

__all__ = (
    "ApprovedDeliveryContract",
    "ApprovedSpikeContract",
    "ApprovedTaskContract",
    "CheckpointReceiptRow",
    "DeliveryValidationPolicy",
    "EVIDENCE_PATTERN",
    "HarnessExecutionRow",
    "InspectedTask",
    "PROPERTY_EXECUTION_HEADERS",
    "PROPERTY_TEST_EVIDENCE_DESTINATION",
    "PROPERTY_TEST_EVIDENCE_HEADING",
    "PropertyExecutionRow",
    "PropertyTestEvidenceRow",
    "TASK_COMPLETION_EVIDENCE_STATUSES",
    "TaskCompletionEvidenceRow",
    "TaskRequirementCoverage",
    "TaskRequirementCoverageResult",
    "TaskSummary",
    "declared_task_waivers",
    "derive_task_requirement_coverage",
    "evidence_timestamp",
    "explicit_human_approver",
    "external_target_contains",
    "inspect_task_blocks",
    "inspect_task_sections",
    "marked_receipt",
    "missing_current_property_task_coverage",
    "parse_checkpoint_git_receipt",
    "parse_checkpoint_rows",
    "parse_observed_property_run",
    "parse_property_test_evidence",
    "parse_release_decision_record",
    "parse_task_completion_evidence",
    "parse_verification_matrix",
    "replay_evidence_matches_contract",
    "require_durable_evidence_source",
    "require_explicit_evidence_value",
    "task_property_execution_table",
    "task_requirement_evidence_dispositions",
    "task_requirement_rules",
    "task_waiver_rows",
    "technology_version_policy_allows",
    "validate_done_evidence",
    "validate_done_property_evidence",
    "validate_gate_b_execution_binding",
    "validate_task_property_execution_projection",
    "validate_task_records",
)
