"""Explicit reviewed exceptions to Fastlane Engine complexity budgets.

This test-policy registry grants no runtime, gate, construction, GitHub, or AWS
authority. Each maximum equals the reviewed 1.3.0 measurement, so growth,
unlisted overages, and obsolete entries fail qualification.
"""

from __future__ import annotations


REVIEWED_MODULE_SIZE_EXCEPTIONS: dict[str, dict[str, int | str]] = {
    "design/diagrams.py": {
        "maximum_lines": 2_223,
        "reviewed_lines": 2_223,
        "reason": "One cohesive diagram contract owns legacy compatibility, semantic binding, portable Mermaid validation, claim safety, and presentation-only repair without a second architecture graph.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
}


REVIEWED_COMPLEXITY_EXCEPTIONS: dict[str, dict[str, int | str]] = {
    "api.py:derive_approved_task_contract": {
        "maximum_lines": 119,
        "maximum_complexity": 16,
        "reviewed_lines": 119,
        "reviewed_complexity": 16,
        "reason": "Public read-only API assembles the complete task contract consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "authority/aws.py:_read_preflight_receipt_authority": {
        "maximum_lines": 122,
        "maximum_complexity": 13,
        "reviewed_lines": 122,
        "reviewed_complexity": 13,
        "reason": "Exact fail-closed authority intersection preserves receipt, scope, expiry, and diagnostic ordering.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "authority/aws.py:_deployment_reconciliation_read_authority": {
        "maximum_lines": 186,
        "maximum_complexity": 32,
        "reviewed_lines": 186,
        "reviewed_complexity": 32,
        "reason": "Exact fail-closed authority intersection preserves receipt, scope, expiry, and diagnostic ordering.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "authority/aws.py:_receipt_external_authority": {
        "maximum_lines": 237,
        "maximum_complexity": 27,
        "reviewed_lines": 237,
        "reviewed_complexity": 27,
        "reason": "Exact fail-closed authority intersection preserves receipt, scope, expiry, and diagnostic ordering.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "authority/aws.py:derive_external_authority": {
        "maximum_lines": 210,
        "maximum_complexity": 47,
        "reviewed_lines": 210,
        "reviewed_complexity": 47,
        "reason": "Exact fail-closed authority intersection preserves receipt, scope, expiry, and diagnostic ordering.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "authority/github.py:_reviewed_script_contract": {
        "maximum_lines": 106,
        "maximum_complexity": 34,
        "reviewed_lines": 106,
        "reviewed_complexity": 34,
        "reason": "Exact fail-closed authority intersection preserves receipt, scope, expiry, and diagnostic ordering.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/deployment.py:_deployment_expected_binding": {
        "maximum_lines": 172,
        "maximum_complexity": 23,
        "reviewed_lines": 172,
        "reviewed_complexity": 23,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/deployment.py:_deployment_row_binding_issues": {
        "maximum_lines": 217,
        "maximum_complexity": 52,
        "reviewed_lines": 217,
        "reviewed_complexity": 52,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/deployment.py:_deployment_historical_authority_proof_issues": {
        "maximum_lines": 123,
        "maximum_complexity": 13,
        "reviewed_lines": 123,
        "reviewed_complexity": 13,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/deployment.py:_deployment_historical_group_issues": {
        "maximum_lines": 137,
        "maximum_complexity": 28,
        "reviewed_lines": 137,
        "reviewed_complexity": 28,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/deployment.py:_deployment_group_projection": {
        "maximum_lines": 109,
        "maximum_complexity": 17,
        "reviewed_lines": 109,
        "reviewed_complexity": 17,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/deployment.py:derive_deployment_sequence_state": {
        "maximum_lines": 634,
        "maximum_complexity": 138,
        "reviewed_lines": 634,
        "reviewed_complexity": 138,
        "reason": "One cohesive ordered external-action state machine preserves receipt-backed attempts and bounded legacy reconciliation without reviving mutation authority.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "PERMANENT",
    },
    "aws/evidence.py:parse_aws_core_evidence": {
        "maximum_lines": 123,
        "maximum_complexity": 38,
        "reviewed_lines": 123,
        "reviewed_complexity": 38,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/evidence.py:validate_advisory_design_binding": {
        "maximum_lines": 68,
        "maximum_complexity": 18,
        "reviewed_lines": 68,
        "reviewed_complexity": 18,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/evidence.py:_unlinked_aws_core_phase_evidence_issues": {
        "maximum_lines": 115,
        "maximum_complexity": 23,
        "reviewed_lines": 115,
        "reviewed_complexity": 23,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/evidence.py:aws_core_phase_evidence_issues": {
        "maximum_lines": 124,
        "maximum_complexity": 24,
        "reviewed_lines": 124,
        "reviewed_complexity": 24,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/lifecycle.py:derive_teardown_route": {
        "maximum_lines": 46,
        "maximum_complexity": 18,
        "reviewed_lines": 46,
        "reviewed_complexity": 18,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/lifecycle.py:derive_aws_execution_projection": {
        "maximum_lines": 78,
        "maximum_complexity": 22,
        "reviewed_lines": 78,
        "reviewed_complexity": 22,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/preflight.py:derive_read_preflight_state": {
        "maximum_lines": 151,
        "maximum_complexity": 35,
        "reviewed_lines": 151,
        "reviewed_complexity": 35,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/teardown.py:_teardown_action_attempt_row_issues": {
        "maximum_lines": 120,
        "maximum_complexity": 20,
        "reviewed_lines": 120,
        "reviewed_complexity": 20,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/teardown.py:_teardown_read_row_issues": {
        "maximum_lines": 117,
        "maximum_complexity": 38,
        "reviewed_lines": 117,
        "reviewed_complexity": 38,
        "reason": "Ordered AWS evidence or lifecycle validation preserves journal chronology without performing an account action.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "aws/teardown.py:derive_teardown_sequence_state": {
        "maximum_lines": 762,
        "maximum_complexity": 158,
        "reviewed_lines": 762,
        "reviewed_complexity": 158,
        "reason": "One cohesive ordered external-action state machine; splitting transitions would obscure chronology, reconciliation, and authority closure.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "PERMANENT",
    },
    "composition.py:derive_context_plan": {
        "maximum_lines": 250,
        "maximum_complexity": 53,
        "reviewed_lines": 250,
        "reviewed_complexity": 53,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "composition.py:_summary_deployment_observation": {
        "maximum_lines": 61,
        "maximum_complexity": 17,
        "reviewed_lines": 61,
        "reviewed_complexity": 17,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "composition.py:derive_document_summary_specifications": {
        "maximum_lines": 256,
        "maximum_complexity": 53,
        "reviewed_lines": 256,
        "reviewed_complexity": 53,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "composition.py:_compose_authority_state": {
        "maximum_lines": 207,
        "maximum_complexity": 22,
        "reviewed_lines": 207,
        "reviewed_complexity": 22,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "composition.py:build_evaluation": {
        "maximum_lines": 573,
        "maximum_complexity": 64,
        "reviewed_lines": 573,
        "reviewed_complexity": 64,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "core/snapshot.py:_synthetic_result": {
        "maximum_lines": 32,
        "maximum_complexity": 17,
        "reviewed_lines": 32,
        "reviewed_complexity": 17,
        "reason": "Reviewed cohesive _synthetic_result contract preserves current deterministic behavior.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/coverage.py:derive_coverage_contract": {
        "maximum_lines": 108,
        "maximum_complexity": 18,
        "reviewed_lines": 108,
        "reviewed_complexity": 18,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/coverage.py:_change_impact_row_issues": {
        "maximum_lines": 95,
        "maximum_complexity": 23,
        "reviewed_lines": 95,
        "reviewed_complexity": 23,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/intake.py:_parse_intake_response_register": {
        "maximum_lines": 201,
        "maximum_complexity": 31,
        "reviewed_lines": 201,
        "reviewed_complexity": 31,
        "reason": "Canonical Define validation preserves provenance and diagnostic order; decimal normalization and contiguity checks bound work to input size instead of the largest supplied ID.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.4",
        "expires": "1.4.0",
    },
    "define/intake.py:_load_intake_tables": {
        "maximum_lines": 122,
        "maximum_complexity": 15,
        "reviewed_lines": 122,
        "reviewed_complexity": 15,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/intake.py:_current_understanding": {
        "maximum_lines": 57,
        "maximum_complexity": 17,
        "reviewed_lines": 57,
        "reviewed_complexity": 17,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/intake.py:_foundation_rows": {
        "maximum_lines": 121,
        "maximum_complexity": 23,
        "reviewed_lines": 121,
        "reviewed_complexity": 23,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/intake.py:_card_question": {
        "maximum_lines": 234,
        "maximum_complexity": 48,
        "reviewed_lines": 233,
        "reviewed_complexity": 47,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/intake.py:_derive_from_tables": {
        "maximum_lines": 144,
        "maximum_complexity": 25,
        "reviewed_lines": 137,
        "reviewed_complexity": 20,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/project.py:brownfield_contract_issues": {
        "maximum_lines": 73,
        "maximum_complexity": 17,
        "reviewed_lines": 73,
        "reviewed_complexity": 17,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/project.py:derive_req_aws_materiality": {
        "maximum_lines": 135,
        "maximum_complexity": 38,
        "reviewed_lines": 135,
        "reviewed_complexity": 38,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/requirements.py:requirement_method_issues": {
        "maximum_lines": 76,
        "maximum_complexity": 16,
        "reviewed_lines": 76,
        "reviewed_complexity": 16,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/requirements.py:quality_attribute_scenario_issues": {
        "maximum_lines": 67,
        "maximum_complexity": 20,
        "reviewed_lines": 67,
        "reviewed_complexity": 20,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/requirements.py:gate_a_method_contract_issues": {
        "maximum_lines": 86,
        "maximum_complexity": 20,
        "reviewed_lines": 86,
        "reviewed_complexity": 20,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/requirements.py:derive_requirements_contract": {
        "maximum_lines": 827,
        "maximum_complexity": 146,
        "reviewed_lines": 827,
        "reviewed_complexity": 146,
        "reason": "Canonical Define validation preserves owner provenance, compatibility, and deterministic Gate A diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:parse_harness_projection_rows": {
        "maximum_lines": 74,
        "maximum_complexity": 20,
        "reviewed_lines": 74,
        "reviewed_complexity": 20,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:parse_property_execution_rows": {
        "maximum_lines": 79,
        "maximum_complexity": 21,
        "reviewed_lines": 79,
        "reviewed_complexity": 21,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:validate_task_property_projection": {
        "maximum_lines": 94,
        "maximum_complexity": 19,
        "reviewed_lines": 94,
        "reviewed_complexity": 19,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:parse_harness_evidence": {
        "maximum_lines": 60,
        "maximum_complexity": 17,
        "reviewed_lines": 60,
        "reviewed_complexity": 17,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:validate_done_harness_evidence": {
        "maximum_lines": 94,
        "maximum_complexity": 20,
        "reviewed_lines": 94,
        "reviewed_complexity": 20,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:validate_task_property_execution_projection": {
        "maximum_lines": 74,
        "maximum_complexity": 19,
        "reviewed_lines": 74,
        "reviewed_complexity": 19,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/evidence.py:validate_done_property_evidence": {
        "maximum_lines": 195,
        "maximum_complexity": 40,
        "reviewed_lines": 195,
        "reviewed_complexity": 40,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/tasks.py:validate_task_snapshot": {
        "maximum_lines": 67,
        "maximum_complexity": 20,
        "reviewed_lines": 67,
        "reviewed_complexity": 20,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/tasks.py:validate_new_build_delivery_order": {
        "maximum_lines": 263,
        "maximum_complexity": 43,
        "reviewed_lines": 263,
        "reviewed_complexity": 43,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/tasks.py:validate_task_graph": {
        "maximum_lines": 441,
        "maximum_complexity": 128,
        "reviewed_lines": 441,
        "reviewed_complexity": 128,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/tasks.py:validate_task_records": {
        "maximum_lines": 143,
        "maximum_complexity": 31,
        "reviewed_lines": 143,
        "reviewed_complexity": 31,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/tasks.py:task_requirement_evidence_dispositions": {
        "maximum_lines": 116,
        "maximum_complexity": 24,
        "reviewed_lines": 116,
        "reviewed_complexity": 24,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "deliver/tasks.py:derive_task_requirement_coverage": {
        "maximum_lines": 125,
        "maximum_complexity": 31,
        "reviewed_lines": 125,
        "reviewed_complexity": 31,
        "reason": "Pure Delivery validation preserves task, evidence, and coverage decisions consumed by the sole mutator.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/adr.py:_parse_adr": {
        "maximum_lines": 91,
        "maximum_complexity": 16,
        "reviewed_lines": 91,
        "reviewed_complexity": 16,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/adr.py:derive_adr_rationale": {
        "maximum_lines": 222,
        "maximum_complexity": 44,
        "reviewed_lines": 222,
        "reviewed_complexity": 44,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/architecture.py:_architecture_tables": {
        "maximum_lines": 99,
        "maximum_complexity": 25,
        "reviewed_lines": 99,
        "reviewed_complexity": 25,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/architecture.py:_derive_architecture_contract": {
        "maximum_lines": 497,
        "maximum_complexity": 109,
        "reviewed_lines": 497,
        "reviewed_complexity": 109,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/diagrams.py:_derive_current_diagram_contract": {
        "maximum_lines": 303,
        "maximum_complexity": 54,
        "reviewed_lines": 303,
        "reviewed_complexity": 54,
        "reason": "One ordered compatibility-aware diagram evaluator preserves semantic digests, presentation-only repair, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "define/project.py:gate_a_product_truth_issues": {
        "maximum_lines": 89,
        "maximum_complexity": 26,
        "reviewed_lines": 89,
        "reviewed_complexity": 26,
        "reason": "One ordered owner-visible Product Agreement validator reconciles exact Gate A readiness and blocker evidence.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/envelope.py:validate_application_source_write_set": {
        "maximum_lines": 50,
        "maximum_complexity": 16,
        "reviewed_lines": 50,
        "reviewed_complexity": 16,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/harness.py:derive_harness_contract": {
        "maximum_lines": 120,
        "maximum_complexity": 23,
        "reviewed_lines": 120,
        "reviewed_complexity": 23,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/project.py:derive_project_design_contract": {
        "maximum_lines": 603,
        "maximum_complexity": 130,
        "reviewed_lines": 603,
        "reviewed_complexity": 130,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/project.py:derive_design_contract": {
        "maximum_lines": 503,
        "maximum_complexity": 103,
        "reviewed_lines": 503,
        "reviewed_complexity": 103,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/source.py:validate_application_source_disposition": {
        "maximum_lines": 90,
        "maximum_complexity": 20,
        "reviewed_lines": 90,
        "reviewed_complexity": 20,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "design/support.py:_iac_validation_issues": {
        "maximum_lines": 109,
        "maximum_complexity": 27,
        "reviewed_lines": 109,
        "reviewed_complexity": 27,
        "reason": "Canonical Design validation preserves traceability, compatibility, and deterministic Gate B diagnostics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "orchestration.py:normalize_gate_b_authority_bounds": {
        "maximum_lines": 119,
        "maximum_complexity": 13,
        "reviewed_lines": 119,
        "reviewed_complexity": 13,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "orchestration.py:evaluate_project": {
        "maximum_lines": 523,
        "maximum_complexity": 82,
        "reviewed_lines": 523,
        "reviewed_complexity": 82,
        "reason": "Top-level immutable composition preserves historical domain order and complete state assembly.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "owner_decisions.py:_derive_gate_b_decision_inventory": {
        "maximum_lines": 148,
        "maximum_complexity": 22,
        "reviewed_lines": 148,
        "reviewed_complexity": 22,
        "reason": "Complete owner projection keeps each required decision and authority boundary together.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "owner_decisions.py:derive_owner_decision_brief": {
        "maximum_lines": 311,
        "maximum_complexity": 40,
        "reviewed_lines": 311,
        "reviewed_complexity": 40,
        "reason": "Complete owner projection keeps each required decision and authority boundary together.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "owner_decisions.py:derive_owner_answer_confirmation": {
        "maximum_lines": 81,
        "maximum_complexity": 18,
        "reviewed_lines": 81,
        "reviewed_complexity": 18,
        "reason": "Complete owner projection keeps each required decision and authority boundary together.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "package/state.py:_validate_project_identity": {
        "maximum_lines": 63,
        "maximum_complexity": 18,
        "reviewed_lines": 63,
        "reviewed_complexity": 18,
        "reason": "Compatibility validation preserves established package-state diagnostic order.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "package/state.py:_validate_execution_plan_and_tasks": {
        "maximum_lines": 63,
        "maximum_complexity": 19,
        "reviewed_lines": 63,
        "reviewed_complexity": 19,
        "reason": "Compatibility validation preserves established package-state diagnostic order.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "package/state.py:_validate_execution_identity": {
        "maximum_lines": 80,
        "maximum_complexity": 20,
        "reviewed_lines": 80,
        "reviewed_complexity": 20,
        "reason": "Compatibility validation preserves established package-state diagnostic order.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_delivery.py:validate_tasks_against_envelope": {
        "maximum_lines": 291,
        "maximum_complexity": 55,
        "reviewed_lines": 291,
        "reviewed_complexity": 55,
        "reason": "Cross-record Delivery composition preserves repository, checkpoint, and envelope intersections.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_delivery.py:validate_checkpoint_record": {
        "maximum_lines": 118,
        "maximum_complexity": 25,
        "reviewed_lines": 118,
        "reviewed_complexity": 25,
        "reason": "Cross-record Delivery composition preserves repository, checkpoint, and envelope intersections.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_delivery.py:validate_construction_repository": {
        "maximum_lines": 234,
        "maximum_complexity": 44,
        "reviewed_lines": 234,
        "reviewed_complexity": 44,
        "reason": "Cross-record Delivery composition preserves repository, checkpoint, and envelope intersections.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_delivery.py:validate_tasks": {
        "maximum_lines": 398,
        "maximum_complexity": 88,
        "reviewed_lines": 398,
        "reviewed_complexity": 88,
        "reason": "Cross-record Delivery composition preserves repository, checkpoint, and envelope intersections.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_inspection.py:_planned_git_queries": {
        "maximum_lines": 117,
        "maximum_complexity": 22,
        "reviewed_lines": 117,
        "reviewed_complexity": 22,
        "reason": "Bounded observation planning preserves one-read snapshot and Git-query semantics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_inspection.py:safe_read_text": {
        "maximum_lines": 53,
        "maximum_complexity": 16,
        "reviewed_lines": 53,
        "reviewed_complexity": 16,
        "reason": "Bounded observation planning preserves one-read snapshot and Git-query semantics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_validation.py:derive_design_contract": {
        "maximum_lines": 75,
        "maximum_complexity": 16,
        "reviewed_lines": 75,
        "reviewed_complexity": 16,
        "reason": "Cross-record PRD composition preserves canonical validation and diagnostic order.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_validation.py:validate_construction_envelope": {
        "maximum_lines": 344,
        "maximum_complexity": 63,
        "reviewed_lines": 344,
        "reviewed_complexity": 63,
        "reason": "Cross-record PRD composition preserves canonical validation and diagnostic order.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "project_validation.py:validate_prd": {
        "maximum_lines": 651,
        "maximum_complexity": 108,
        "reviewed_lines": 651,
        "reviewed_complexity": 108,
        "reason": "Cross-record PRD composition preserves canonical validation and diagnostic order.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "remediation.py:_agent_correction_is_safe": {
        "maximum_lines": 74,
        "maximum_complexity": 25,
        "reviewed_lines": 74,
        "reviewed_complexity": 25,
        "reason": "One ordered remediation decision preserves responsible-party and owner-action semantics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "remediation.py:derive_remediation": {
        "maximum_lines": 157,
        "maximum_complexity": 36,
        "reviewed_lines": 157,
        "reviewed_complexity": 36,
        "reason": "One ordered remediation decision preserves responsible-party and owner-action semantics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "remediation.py:derive_interaction": {
        "maximum_lines": 308,
        "maximum_complexity": 69,
        "reviewed_lines": 308,
        "reviewed_complexity": 69,
        "reason": "One ordered remediation decision preserves responsible-party and owner-action semantics.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
    "routing.py:derive_route": {
        "maximum_lines": 61,
        "maximum_complexity": 23,
        "reviewed_lines": 61,
        "reviewed_complexity": 23,
        "reason": "One ordered route decision prevents overlapping lifecycle outcomes.",
        "risk": "Further growth can obscure fail-closed diagnostic order or ownership; exact measurements and expiry force a new bounded review.",
        "reviewed_in": "1.3.0",
        "expires": "1.4.0",
    },
}
