"""Fastlane AWS evidence and lifecycle state projections.

The package consumes observed canonical records and explicit authority inputs.
It performs no AWS calls and cannot approve, authorize, deploy, or tear down.
"""

from .deployment import (
    derive_deployment_sequence_state,
    validated_deployment_release_cutoff,
)
from .evidence import (
    aws_core_evidence_diagnostic_code,
    aws_core_phase_evidence_issues,
    derive_aws_core_observed_usage,
    parse_aws_core_evidence,
    parse_deployment_reconciliation_evidence,
    parse_read_preflight_evidence,
    parse_teardown_reconciliation_evidence,
    validate_advisory_design_binding,
)
from .lifecycle import (
    aws_deployment_teardown_sequence_conflict,
    aws_lifecycle_intent_route_is_eligible,
    derive_aws_delivery_route,
    derive_aws_execution_projection,
    derive_aws_residual_disposition,
    derive_teardown_route,
    parse_aws_lifecycle_intent_record,
    release_lifecycle_intent_boundary_is_settled,
)
from .models import (
    AWS_CORE_EVIDENCE_HEADERS,
    AWS_CORE_EVIDENCE_HEADERS_V1,
    AWS_CORE_EVIDENCE_PHASES,
    AWS_CORE_EVIDENCE_STATUSES,
    AWS_CORE_REQUIRED_CAPABILITIES,
    AWS_DEPLOYMENT_ACTION_STATUSES,
    AWS_DEPLOYMENT_ATTEMPT_ID,
    AWS_DEPLOYMENT_EVIDENCE_HEADERS,
    AWS_DEPLOYMENT_EVIDENCE_HEADING,
    AWS_DEPLOYMENT_PRECALL_RESULT,
    AWS_DEPLOYMENT_READ_PROVENANCE,
    AWS_DEPLOYMENT_RECEIPT_FIELDS,
    AWS_DEPLOYMENT_RECONCILIATION_STATUSES,
    AWS_DEPLOYMENT_TERMINAL_STATUSES,
    AWS_LIFECYCLE_INTENT_SOURCE,
    AWS_LIFECYCLE_INTENT_VALUES,
    AWS_PLAN_BINDING,
    AWS_PREFLIGHT_ID,
    AWS_READ_AUTHORIZATION_ID,
    AWS_READ_ONLY_OPERATION,
    AWS_READ_PREFLIGHT_HEADERS,
    AWS_READ_PREFLIGHT_HEADING,
    AWS_READ_PREFLIGHT_RECEIPT_FIELDS,
    AWS_TEARDOWN_ACTION_STATUSES,
    AWS_TEARDOWN_ATTEMPT_ID,
    AWS_TEARDOWN_EVIDENCE_HEADERS,
    AWS_TEARDOWN_EVIDENCE_HEADING,
    AWS_TEARDOWN_PRECALL_RESULT,
    AWS_TEARDOWN_READ_PROVENANCE,
    AWS_TEARDOWN_RECEIPT_FIELDS,
    AWS_TEARDOWN_REVIEW_STATUSES,
    AWS_TEARDOWN_TERMINAL_STATUSES,
    AwsAuthorityPolicy,
    AwsCoreEvidenceRow,
)
from .preflight import derive_read_preflight_state
from .teardown import derive_teardown_sequence_state


__all__ = (
    "AWS_CORE_EVIDENCE_HEADERS",
    "AWS_CORE_EVIDENCE_HEADERS_V1",
    "AWS_CORE_EVIDENCE_PHASES",
    "AWS_CORE_EVIDENCE_STATUSES",
    "AWS_CORE_REQUIRED_CAPABILITIES",
    "AWS_DEPLOYMENT_ACTION_STATUSES",
    "AWS_DEPLOYMENT_ATTEMPT_ID",
    "AWS_DEPLOYMENT_EVIDENCE_HEADERS",
    "AWS_DEPLOYMENT_EVIDENCE_HEADING",
    "AWS_DEPLOYMENT_PRECALL_RESULT",
    "AWS_DEPLOYMENT_READ_PROVENANCE",
    "AWS_DEPLOYMENT_RECEIPT_FIELDS",
    "AWS_DEPLOYMENT_RECONCILIATION_STATUSES",
    "AWS_DEPLOYMENT_TERMINAL_STATUSES",
    "AWS_LIFECYCLE_INTENT_SOURCE",
    "AWS_LIFECYCLE_INTENT_VALUES",
    "AWS_PLAN_BINDING",
    "AWS_PREFLIGHT_ID",
    "AWS_READ_AUTHORIZATION_ID",
    "AWS_READ_ONLY_OPERATION",
    "AWS_READ_PREFLIGHT_HEADERS",
    "AWS_READ_PREFLIGHT_HEADING",
    "AWS_READ_PREFLIGHT_RECEIPT_FIELDS",
    "AWS_TEARDOWN_ACTION_STATUSES",
    "AWS_TEARDOWN_ATTEMPT_ID",
    "AWS_TEARDOWN_EVIDENCE_HEADERS",
    "AWS_TEARDOWN_EVIDENCE_HEADING",
    "AWS_TEARDOWN_PRECALL_RESULT",
    "AWS_TEARDOWN_READ_PROVENANCE",
    "AWS_TEARDOWN_RECEIPT_FIELDS",
    "AWS_TEARDOWN_REVIEW_STATUSES",
    "AWS_TEARDOWN_TERMINAL_STATUSES",
    "AwsAuthorityPolicy",
    "AwsCoreEvidenceRow",
    "aws_core_evidence_diagnostic_code",
    "aws_core_phase_evidence_issues",
    "aws_deployment_teardown_sequence_conflict",
    "aws_lifecycle_intent_route_is_eligible",
    "derive_aws_core_observed_usage",
    "derive_aws_delivery_route",
    "derive_aws_execution_projection",
    "derive_aws_residual_disposition",
    "derive_deployment_sequence_state",
    "validated_deployment_release_cutoff",
    "derive_read_preflight_state",
    "derive_teardown_route",
    "derive_teardown_sequence_state",
    "parse_aws_core_evidence",
    "parse_aws_lifecycle_intent_record",
    "parse_deployment_reconciliation_evidence",
    "parse_read_preflight_evidence",
    "parse_teardown_reconciliation_evidence",
    "release_lifecycle_intent_boundary_is_settled",
    "validate_advisory_design_binding",
)
